csd_Capstone/Moffet_bay/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
from . import views
from .views import CustomPasswordResetView



urlpatterns = [
      path('sign_in/', views.sign_in, name='sign_in'),
      path('sign_up/', views.sign_up, name='sign_up'),
    
      path('', views.index , name='index'),
      path('success/', views.success, name='success'),
      path('reservation/', views.reservation, name='reservation'),
      path('about/', views.about, name='about'),
      path('profile/', views.profile, name='profile'),
      path('contact/', views.contact, name='contact'),
      path('attractions/', views.attractions, name='attractions'),

      path('reservation_summary/', views.reservation_summary, name='reservation_summary'),
     
  
      
      path('logout/', LogoutView.as_view(template_name='logout.html'), name='logout'),
     
       path('docs/', views.docs_view, name='docs'),
       path('reservation_lookup/', views.reservation_lookup, name='reservation_lookup'),
        path('my-reservations/', views.reservation_history, name='reservation_history'),
    path('past-reservations/', views.past_reservations, name='past_reservations'),
    path('future-reservations/', views.future_reservations, name='future_reservations'),
    path('create-reservation/', views.create_reservation, name='create_reservation'),
   path('room_rates/', views.room_rates, name='room_rates'),
    path('reservation-lookup/', views.reservation_lookup, name='reservation_lookup'),
    path('reservation_lookup_results/', views.reservation_lookup_results, name='reservation_lookup_results'),
     path('password_reset/', views.password_reset, name='password_reset'),
    path('password_reset_done/', views.password_reset_done, name='password_reset_done'),
      path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
       path('restaurant-reservation/', views.restaurant_reservation, name='restaurant_reservation'),
    
   
       
      
     
]

csd_Capstone/csd_Capstone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("Moffet_bay.urls")),
    path("admin/", admin.site.urls),
    
]

csd_Capstone/Moffet_bay/models.py
import markdown
from django.conf import settings
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                        PermissionsMixin, User)
from django.db import models
from django.utils.text import slugify


class Attractions(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name



class User(models.Model):
    username = models.CharField(max_length=150, unique=True)
    password_hash = models.CharField(max_length=255)

    def __str__(self):
        return self.username
    
  
class CustomUserManager(BaseUserManager):
    def create_user(self, username, email, password=None, **extra_fields):
        if not username:
            raise ValueError('The Username field is required')
        if not email:
            raise ValueError('The Email field is required')
        
        
        email = self.normalize_email(email)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    
    def create_superuser(self, username, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(username, email, password, **extra_fields)
    
    
    
    
class CustomUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=150, unique=True)
    email = models.EmailField(max_length=254, unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    first_name = models.CharField(max_length=100, blank=True, null=True)
    last_name = models.CharField(max_length=100, blank=True, null=True)
    street = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    state = models.CharField(max_length=100, blank=True, null=True)
    zip_code = models.CharField(max_length=20, blank=True, null=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.username


    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return self.is_admin


  
class Reservation(models.Model):
    reservation_id = models.CharField(max_length=10, unique=True, editable=False)
    email = models.EmailField(max_length=254, blank=False, null=False)  
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    street = models.CharField(max_length=255)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    zip = models.CharField(max_length=20)
    guests = models.IntegerField()
    room_type = models.CharField(max_length=50, choices=[('single', 'Single'), ('double', 'Double'), ('suite', 'Suite')])
    check_in = models.DateField()
    check_out = models.DateField()
    reservation_date = models.DateField(null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.reservation_id:
            self.reservation_id = self.generate_reservation_id()
        super().save(*args, **kwargs)

    def generate_reservation_id(self):
        import random
        import string
        letters = ''.join(random.choices(string.ascii_uppercase, k=2))
        numbers = ''.join(random.choices(string.digits, k=6))
        reservation_id = f"{letters}{numbers}"
        
        while Reservation.objects.filter(reservation_id=reservation_id).exists():
            letters = ''.join(random.choices(string.ascii_uppercase, k=2))
            numbers = ''.join(random.choices(string.digits, k=6))
            reservation_id = f"{letters}{numbers}"
        
        return reservation_id

    def __str__(self):
        return f"{self.reservation_id} - {self.first_name} {self.last_name} - {self.room_type} - {self.check_in} to {self.check_out} - {self.email}"

class Testimonial(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.first_name} - {self.message[:50]}"


    
  

class ContactMessage(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Message from {self.name} ({self.email})"
    
 

class RestaurantReservation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone = models.CharField(max_length=15)
    date = models.DateField()
    time = models.TimeField()
    guests = models.IntegerField()
    special_requests = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} - {self.date} at {self.time}"

csd_Capstone/Moffet_bay/views.py
import json
from datetime import date

from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.utils import timezone

from .forms import (ContactMessageForm, ReservationForm, ReservationLookupForm,
                    RestaurantReservationForm, SignInForm, SignUpForm,
                    TestimonialForm)
from .models import (Attractions, CustomUser, Reservation,
                     RestaurantReservation, Testimonial)


def attractions(request):
    attractions = [
        {
            "title": "Diving",
            "description": "Dive into the underwater world and explore vibrant marine life with our certified diving instructors.",
            "price": "$120 per person",
            "duration": "4 hours",
            "image_url": "https://images.unsplash.com/photo-1561983779-7d7e065befa4?q=80&w=1589&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        },
        {
            "title": "Hiking",
            "description": "Discover scenic trails and enjoy the great outdoors with our guided hiking tours.",
            "price": "$30 per person",
            "duration": "4 hours",
            "image_url": "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0",
        },
        {
            "title": "Boating",
            "description": "Relax on the water with our boating excursions, perfect for families and groups.",
            "price": "$60 per person",
            "duration": "2 hours",
            "image_url": "https://images.unsplash.com/photo-1559075471-b8a6c70b56c2?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fGJvYXRpbmd8ZW58MHx8MHx8fDI%3D",
        },
        {
            "title": "Paddle Boarding",
            "description": "Explore peaceful waters and improve your balance with our paddle boarding adventures.",
            "price": "$45 per person",
            "duration": "2 hours",
            "image_url": "https://images.unsplash.com/photo-1472745942893-4b9f730c7668",
        },
        {
            "title": "Whale Watching",
            "description": "Experience the majesty of marine life up close with our guided whale watching tours.",
            "price": "$99 per person",
            "duration": "3 hours",
            "image_url": "https://images.unsplash.com/photo-1568430462989-44163eb1752f",
        },
        {
            "title": "Spa Day",
            "description": "Unwind with a relaxing massage, facial, and access to the resort’s wellness facilities.",
            "price": "$150 per person",
            "duration": "3 hours",
            "image_url": "https://images.unsplash.com/photo-1630893174210-eea582de3c74?q=80&w=1528&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        },
    ]
    return render(request, "attractions.html", {"attractions": attractions})


def index(request):
    return render(request, "index.html")


def success(request):
    return render(request, "success.html")


def sign_up(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful. You are now logged in.")
            return redirect("index")  # Redirect to your desired page after sign-up
        else:
            messages.error(request, "Please correct the errors below.")
    else:
        form = SignUpForm()

    return render(request, "sign_up.html", {"form": form})


def sign_in(request):
    if request.method == "POST":
        form = SignInForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            messages.success(request, "Login successful.")
            return redirect("index")  # Redirect to your desired page after sign-in
        else:
            messages.error(request, "Invalid username or password.")
    else:
        form = SignInForm()

    return render(request, "sign_in.html", {"form": form})


def reservation(request):
    if request.user.is_authenticated:
        # Auto-fill form with logged-in user's details
        user = request.user
        initial_data = {
            "first_name": user.first_name,
            "last_name": user.last_name,
            "street": user.street,
            "city": user.city,
            "state": user.state,
            "zip": user.zip_code,
        }
    else:
        initial_data = {}

    if request.method == "POST":
        form = ReservationForm(request.POST)
        if form.is_valid():
            reservation = form.save(commit=False)
            if request.user.is_authenticated:
                reservation.user = request.user  # Link reservation to user
            reservation.save()
            return redirect("success")
    else:
        form = ReservationForm(initial=initial_data)  # Pre-fill form

    return render(request, "reservation.html", {"form": form})


def about(request):
    testimonials = Testimonial.objects.all().order_by(
        "-created_at"
    )  # Fetch all testimonials
    form = TestimonialForm()

    if request.method == "POST":
        form = TestimonialForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("about")  # Redirect to refresh page after submission

    return render(request, "about.html", {"testimonials": testimonials, "form": form})


def profile(request):
    return render(request, "profile.html")


def contact_page(request):
    return render(request, "contact.html")


def reservation_summary(request):
    if request.user.is_authenticated:
        user = request.user
        today = timezone.now().date()
        past_reservations = Reservation.objects.filter(
            user=user, reservation_date__lt=today
        )
        upcoming_reservations = Reservation.objects.filter(
            user=user, reservation_date__gte=today
        )
        context = {
            "past_reservations": past_reservations,
            "upcoming_reservations": upcoming_reservations,
        }
        return render(request, "reservation_summary.html", context)
    else:
        # Redirect to login page or show an error
        return redirect("sign_in")


@login_required
def create_reservation(request):
    if request.method == "POST":
        form = ReservationForm(request.POST)
        if form.is_valid():
            reservation = form.save(commit=False)
            reservation.user = request.user
            reservation.save()
            return redirect("reservation_summary")
    else:
        form = ReservationForm()
    return render(request, "create_reservation.html", {"form": form})


def docs_view(request):
    return render(request, "docs.html")


@login_required
def reservation_history(request):
    today = date.today()
    return render(request, "reservations/history.html", {"today": today})


@login_required
def past_reservations(request):
    today = date.today()
    reservations = Reservation.objects.filter(
        user=request.user, check_out__lt=today
    ).order_by("-check_out")

    return render(
        request, "reservations/past_reservations.html", {"reservations": reservations}
    )


@login_required
def future_reservations(request):
    today = date.today()
    reservations = Reservation.objects.filter(
        user=request.user, check_in__gte=today
    ).order_by("check_in")

    return render(
        request, "reservations/future_reservations.html", {"reservations": reservations}
    )


def register(request):
    return render(request, "register.html")


def check_user(request):
    return render(request, "check_user.html")


def room_rates(request):
    return render(request, "room_rates.html")


def contact(request):
    if request.method == "POST":
        form = ContactMessageForm(request.POST)
        if form.is_valid():
            form.save()
            #  success message using Django's messages framework.
            messages.success(request, "Message sent successfully.")
            return redirect(
                "contact"
            )  # Redirect back to the contact page or to a thank-you page.
    else:
        form = ContactMessageForm()

    return render(request, "contact.html", {"form": form})


def password_reset(request):
    return render(request, "password_reset.html")


def password_reset_done(request):
    return render(request, "password_reset_done.html")


class CustomPasswordResetView(SuccessMessageMixin, PasswordResetView):
    template_name = "password_reset.html"
    email_template_name = "password_reset_email.html"
    subject_template_name = "password_reset_subject.txt"
    success_url = reverse_lazy("password_reset_done")
    success_message = "A password reset link has been sent to your email."


def reservation_lookup(request):
    print("View called")
    print("Headers:", request.headers)  # Debug headers
    print("Is HTMX:", request.htmx)  # Debug HTMX status

    form = ReservationLookupForm(request.POST or None)
    results = None

    if request.method == "POST" and form.is_valid():
        print("Form data:", form.cleaned_data)  # Debug form data

        reservation_id = form.cleaned_data.get("reservation_id")
        last_name = form.cleaned_data.get("last_name")
        email = form.cleaned_data.get("email")

        query = Q()
        if reservation_id:
            query &= Q(reservation_id__icontains=reservation_id)
        if last_name:
            query &= Q(last_name__icontains=last_name)
        if email:

csd_Capstone/Moffet_bay/templates/about.html
{% extends 'base.html' %}
{% block title %}About{% endblock %} 

{% block content %}
{% load static %}
<style>
    footer {
        position: absolute;
        bottom: 0;
        width: 100%;
    }
</style>
<div class="container my-5">
    <main>
    <h2 class="text-center">What Our Guests Say</h2>
    
    <div class="table-responsive">
        <table class="table table-bordered mt-3">
            <thead>
                <tr>
                    <th>First Name</th>
                    <th>Testimonial</th>
                </tr>
            </thead>
            <tbody>
                {% for testimonial in testimonials %}
                <tr>
                    <td>{{ testimonial.first_name }}</td>
                    <td>{{ testimonial.last_name }}</td>
                    <td>{{ testimonial.message }}</td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="2" class="text-center">No testimonials yet. Be the first to leave one!</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <!-- Testimonial Submission Form -->
    <h3 class="text-center mt-4">Leave a Testimonial</h3>
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_first_name" class="form-label">Your Name</label>
            {{ form.first_name }}
        </div>
        <div class="mb-3">
            <label for="id_message" class="form-label">Your Testimonial</label>
            {{ form.message }}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
</main>

{% endblock %}

csd_Capstone/Moffet_bay/templates/history.html
# templates/reservations/history.html
{% extends 'base.html' %}

{% block content %}
<div class="container mx-auto px-4 py-8">
    <h1 class="text-3xl font-bold mb-6">My Reservations</h1>
    
    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <!-- Future Reservations -->
        <div class="bg-white p-6 rounded-lg shadow">
            <h2 class="text-xl font-semibold mb-4">Upcoming Stays</h2>
            <div id="future-reservations"
                 hx-get="{% url 'future_reservations' %}"
                 hx-trigger="load"
                 hx-swap="innerHTML">
                <div class="animate-pulse">
                    <div class="h-4 bg-gray-200 rounded w-3/4 mb-4"></div>
                    <div class="h-4 bg-gray-200 rounded w-1/2 mb-4"></div>
                    <div class="h-4 bg-gray-200 rounded w-2/3"></div>
                </div>
            </div>
        </div>

        <!-- Past Reservations -->
        <div class="bg-white p-6 rounded-lg shadow">
            <h2 class="text-xl font-semibold mb-4">Past Stays</h2>
            <div id="past-reservations"
                 hx-get="{% url 'past_reservations' %}"
                 hx-trigger="load"
                 hx-swap="innerHTML">
                <div class="animate-pulse">
                    <div class="h-4 bg-gray-200 rounded w-3/4 mb-4"></div>
                    <div class="h-4 bg-gray-200 rounded w-1/2 mb-4"></div>
                    <div class="h-4 bg-gray-200 rounded w-2/3"></div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

csd_Capstone/Moffet_bay/templates/index.html
{% extends "base.html" %} 
{% block title %}Home{% endblock %} 

{% block content %}
{% load static %}

<!-- Hero Section -->
<div class="container-fluid bg-light py-5">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-6">
        <h1 class="display-4 fw-bold">Moffat Bay Resort</h1>
        <p class="lead">An oasis of love and money baby. All you have to do, is nothing.</p>
        <p class="lead">We have the best rooms, the best food, and the best service. Register now for the best deals!</p>
        <a href="{% url 'sign_up' %}" class="btn btn-primary btn-lg">Register</a>
      </div>
      <div class="col-md-6">
        <img src="{% static '/images/resort1.jpg' %}" class="img-fluid" alt="Resort view">
      </div>
    </div>
  </div>
</div>

<div class="b-example-divider"></div>

<!-- Rewards Cards Section -->
<div class="container px-4 py-5" id="custom-cards">
  <h2 class="pb-2 border-bottom">Why Choose Moffat Bay</h2>

  <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5">
    <div class="col">
      <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg">
        <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
          <h3 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">Get Rewards and Exclusive Offers</h3>
          <ul class="d-flex list-unstyled mt-auto">
            <li class="me-auto">
              <img src="{% static '/images/check-in.jpg' %}" alt="Check-in icon" width="32" height="32" class="rounded-circle border border-white">
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="col">
      <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg">
        <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
          <h3 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">Build Points for Future Trips</h3>
          <ul class="d-flex list-unstyled mt-auto">
            <li class="me-auto">
              <img src="{% static '/images/resort2.jpg' %}" alt="Resort icon" width="32" height="32" class="rounded-circle border border-white">
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="col">
      <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg">
        <div class="d-flex flex-column h-100 p-5 pb-3 text-shadow-1">
          <h3 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">Come See What You're Missing</h3>
          <ul class="d-flex list-unstyled mt-auto">
            <li class="me-auto">
              <img src="{% static '/images/pool.jpg' %}" alt="Pool icon" width="32" height="32" class="rounded-circle border border-white">
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="b-example-divider"></div>



<!-- Restaurant Section -->
<div class="container-fluid bg-dark text-white py-5">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-6">
        <h1 class="display-4 fw-bold">Moffat Bay Restaurant</h1>
        <p class="lead">Indulge in a world-class dining experience with breathtaking views and exquisite flavors.</p>
        <p class="lead">From fresh seafood to gourmet steaks, our chefs craft dishes that leave a lasting impression.</p>
        <a href="{% url 'restaurant_reservation' %}" class="btn btn-outline-primary">Reserve a Table</a>
      </div>
      <div class="col-md-6">
        <img src="{% static '/images/fishWhiteBack.png' %}" class="img-fluid rounded" alt="Restaurant showcase">
      </div>
    </div>
  </div>
</div>

<div class="container-fluid  text-black py-5">

</div>




{% endblock %}

csd_Capstone/Moffet_bay/templates/logout.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-5">
    <h1 class="text-center">You have been logged out</h1>
</div>
{% endblock %}

csd_Capstone/Moffet_bay/templates/messages.html
<!-- {% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %} -->

csd_Capstone/Moffet_bay/templates/password_reset.html
{% extends "base.html" %}
{% block title %}Reset Password{% endblock %}

{% block content %}
<style>
    footer {
        position: absolute;
        bottom: 0;
        width: 100%;
    }
</style>
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow-lg">
                <div class="card-body">
                    <h2 class="text-center mb-4">Reset Your Password</h2>
                    <p class="text-muted text-center">Enter your email address, and we will send you instructions to reset your password.</p>

                    <form method="POST">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="email" class="form-label">Email Address</label>
                            <input type="email" name="email" id="email" class="form-control" required>
                        </div>
                        <button type="submit" class="btn btn-primary w-100">Send Reset Link</button>
                    </form>

                    {% if messages %}
                        <div class="mt-3">
                            {% for message in messages %}
                                <div class="alert alert-info">{{ message }}</div>
                            {% endfor %}
                        </div>
                    {% endif %}

                    <div class="text-center mt-3">
                        <a href="{% url 'sign_in' %}" class="text-decoration-none">Back to Login</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

csd_Capstone/Moffet_bay/templates/past_reservation.html
{% extends 'base.html' %}

{% block title %}Reservation Lookup{% endblock %}

{% block content %}
<main class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h1 class="text-center mb-4">Reservation Lookup</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Search</button>
            </form>
            {% if results %}
                <h2 class="mt-4">Results:</h2>
                <ul>
                    {% for reservation in results %}
                        <li>{{ reservation }}</li>
                    {% empty %}
                        <li>No reservations found.</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
</main>
{% endblock %}

csd_Capstone/Moffet_bay/templates/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid bg-body-secondary vh-100">
    <div class="modal modal-sheet position-static d-block bg-body-secondary p-4 py-md-5">
        <div class="modal-dialog">
            <div class="modal-content rounded-4 shadow">
                <div class="modal-header border-bottom-0">
                    <h5 class="modal-title">Room Reservation</h5>
                </div>
                <div class="modal-body">
    <h1 class="text-center">Profile</h1>
    <p>Username: {{ user.username }}</p>
    <p>Email: {{ user.email }}</p>
    <h2>Reservations</h2>
    {% for reservation in user.reservation_set.all %}
        <p>Room Type: {{ reservation.room_type }}</p>
        <p>Check-in: {{ reservation.check_in }}</p>
        <p>Check-out: {{ reservation.check_out }}</p>
        <hr>
    {% empty %}
        <p>You have no past reservations.</p>
    {% endfor %}

    {% if user.reservation_set.all %}
        <a href="{% url 'reservation' %}" class="btn btn-primary">Make a Reservation</a>
    {% endif %}
</div>
</div>
</div>
</div>
</div>

{% endblock %}

csd_Capstone/Moffet_bay/templates/restaurant_reservation.html
{% extends "base.html" %}
{% block title %}Restaurant Reservation{% endblock %}

{% block content %}
<div class="container py-5">
    <h1 class="text-center">Reserve a Table</h1>
    <form method="post" class="mt-4">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Name</label>
            {{ form.name }}
        </div>
        <div class="mb-3">
            <label class="form-label">Email</label>
            {{ form.email }}
        </div>
        <div class="mb-3">
            <label class="form-label">Phone</label>
            {{ form.phone }}
        </div>
        <div class="mb-3">
            <label class="form-label">Date</label>
            {{ form.date }}
        </div>
        <div class="mb-3">
            <label class="form-label">Time</label>
            {{ form.time }}
        </div>
        <div class="mb-3">
            <label class="form-label">Number of Guests</label>
            {{ form.guests }}
        </div>
        <div class="mb-3">
            <label class="form-label">Special Requests</label>
            {{ form.special_requests }}
        </div>
        <button type="submit" class="btn btn-primary">Reserve</button>
    </form>
</div>
{% endblock %}